### ISSUE TITLE
공통 응답 모델이 필요합니다.

### ISSUE THREAD

**Issue by kor-Chipmunk** [mash-up-kr/Dionysos-Backend#29]
## 목적
클라이언트에서 처리하기 쉽도록 공통 응답 모델을 만들 필요가 있습니다.
어떤 요청은 다른 형식의 응답 모델을 사용하고 어떤 요청은 HTTP 응답 코드만으로 확인을 해야 하니
클라이언트의 하드 코딩이 예상됩니다.

따라서 오류가 발생했다면 자체 코드와 여러 오류 메시지들을 담아 보내주고
정상적인 요청이라면 마찬가지로 자체 코드와 요청한 데이터를 담아 보내주는
응답 모델을 만들어야 합니다.

## 작업 상세 내용
- [x] 공통 응답 모델 구조 설계
- [x] 자체 코드 설계
- [x] 리팩터링으로 모든 응답에 적용
- [x] 클라이언트에게 형식 알리기

## 참고사항
백엔드 개발자끼리, 또는 프론트엔드 개발자와 디자이너와 함께 회의로 논의해봐야 할 것으로 예상합니다!

**Comment by kor-Chipmunk** [comment]
common 패키지 아래에 `DionysosAPIResponse` 클래스를 생성했습니다.
현재 속성은 `code`, `message`, `data` 속성으로 이루어져 있습니다.
HTTP 응답 코드와 서버 자체 코드와 관련해서 어떤 구조가 효율적인지 프론트와 이야기 해보려고 합니다.
더불어서 오류 모델의 구조도 생각해볼 필요가 있습니다.

**Comment by kor-Chipmunk** [comment]
현재는 SpringApplication 와 같은 패키지에서 exception 패키지를 만들어서 관리를 하고 있습니다.
주로 User 서비스와 관련한 예외처리들이 있는데요.
다른 서비스의 예외 클래스 도입도 필요해보입니다.
각 도메인 영역으로 `exception` 패키지를 옮기면은 명확히 알 수 있을 것 같습니다.

**Comment by MiHyunee** [comment]
TImeHistory 도메인에서 get요청이 오면 사용자의 현재까지의 duration을 보내주는 api를 만들고 있습니다.
이 때, 당일 날짜에 해당하는 historyDay가 있는지 쿼리문으로 확인을 하고,
있으면 entity로 받아 dto로 return을 하고,
없는 경우 일단 exception처리를 하였습니다.
제가 궁금한건, 해당 날짜의 기록이 없는 경우 누적 공부시간 0분을 화면에 출력해야하는데,
백에서 exception으로 내보내 주면 그 예외를 프론트에서 받아 프론트에서 0분으로 뷰에 출력하도록 할 수 있을 까요?
프론트에서 불가능하다면 Optional로 query문을 받는 상황에서 제가 할 수 있는 좋은 해결방안은 무엇이 있을까요?

**Comment by kor-Chipmunk** [comment]
@MiHyunee 프론트에서도 예외처리 할 수 있습니당! 그런데 생각해보면 누적 시간이 없는게 오류는 아니지 않을까용? 결과가 없는 경우에도 Dto 로 만들지 못할 이유가 있을까요?

**Comment by kor-Chipmunk** [comment]
> 현재는 SpringApplication 와 같은 패키지에서 exception 패키지를 만들어서 관리를 하고 있습니다.
> 주로 User 서비스와 관련한 예외처리들이 있는데요.
> 다른 서비스의 예외 클래스 도입도 필요해보입니다.
> 각 도메인 영역으로 `exception` 패키지를 옮기면은 명확히 알 수 있을 것 같습니다.

예외로 만드는 작업은 공통 응답 모델과는 상관 없으니 따로 이슈를 발행해야 할 것 같습니다~

**Comment by kor-Chipmunk** [comment]
자체 API 응답 코드는 러프하게 만들었습니다.
아직까지 코드를 따로 만들어야 할 필요성이 없기에 후에 프론트와 상의해보기로 하죠!
