### ISSUE TITLE
리드미를 만들어본다.

### ISSUE THREAD

**Issue by kor-Chipmunk** [mash-up-kr/Dionysos-Backend#42]
## 목적
리드미를 만들어 프로젝트를 설명하는 문서를 만든다.

## 작업 상세 내용
- [x] README.md 파일에 들어갈 항목 설정
- [x] 업로드

**Comment by kor-Chipmunk** [comment]
< 항목 >
1. 프로젝트 소개
2. 앱 다운로드 링크
3. 프로젝트 빌드 방법
4. 기여 방법 (이슈, PR)
5. 이메일

**Comment by MiHyunee** [comment]
API 문서도 swagger를 활용해 첨부하면 좋을 것 같습니다!

**Comment by kor-Chipmunk** [comment]
> API 문서도 swagger를 활용해 첨부하면 좋을 것 같습니다!

readme 텍스트에 swagger 링크도 붙이면 좋다는 말씀인가용~?

**Comment by MiHyunee** [comment]
> > API 문서도 swagger를 활용해 첨부하면 좋을 것 같습니다!
> 
> readme 텍스트에 swagger 링크도 붙이면 좋다는 말씀인가용~?

링크도 좋고, API양이 적다면 캡쳐해서 이미지로 첨부해도 좋을 것 같아요!
