### ISSUE TITLE
누적 시간 기록 도메인 만들기

### ISSUE THREAD

**Issue by kor-Chipmunk** [mash-up-kr/Dionysos-Backend#5]
## 목적
누적 시간 기록의 요청을 담당합니다.

## 작업할 것
- [x] Entity 설계
- [x] Service 비즈니스 로직 작성
- [x] RestController 요청 지점 생성
- [x] 랭킹 로직 작성
- [x] Create/Update 수정

## 참고사항
없습니다.

**Comment by MiHyunee** [comment]
하루의 첫 시작 이벤트일 때는 Post로, 이후의 일시정지/종료/재시작 이벤트일 때는 Put메소드로 받도록 했는데
클라이언트에서 첫 시작 이벤트임을 알아차리기가 불가능하지 않나요?
그렇다면 메소드를 통일시킨 후에 백에서 디비 조회 후 create인지 update인지 구분 하여 디비에 저장해야 하는데 어떤 좋은 방법이 있을까요?
일단 Post와 Put으로 구분해두었습니다.

**Comment by kor-Chipmunk** [comment]
클라이언트에서 첫 시작을 구분하고 캐싱하는 로직이 필요한데, 단순 메소드 구분을 위해 클라이언트에서 쓰는 비용이 크다고 느낍니다!
둘 다 POST 메소드로 받는 것이 바람직하네요.

**Comment by kor-Chipmunk** [comment]
가장 최근 데이터의 필드 중 현재 시작 중인지 알려주는 `run` 필드를 확인하면 되지 않을까요?
시작 요청지점에서는
- 데이터가 없거나(신규유저)
- 오늘 날짜가 아니거나
- 오늘 날짜여도 `run` 필드가 `false` 라면

오늘 날짜의 데이터를 처음으로 만들거나, 오늘 날짜의 데이터의 `run` 필드를 `true`로 바꾸는 로직을 따라가면 되지 않을까 싶네요!

**Comment by kor-Chipmunk** [comment]
단순하게 시작 `public ResponseEntity<?> start(...)` 메소드와 `public ResponseEntity<?> stop(...)` 메소드만 구현하면 되지 않을까 싶네요!

**Comment by kor-Chipmunk** [comment]
정지 요청지점에서는
- 오늘 데이터가 있고
- `run` 필드가 `true` 이면

`run` 필드를 `false` 로 바꾸고
요청으로 넘어온 날짜와 최근 시작 날짜를 연산해 `duration`을 계산해 수정하는 로직을 따라가면 되겠군요.

**Comment by kor-Chipmunk** [comment]
리팩터링 PR이 머지가 되면은, 누적 시간 브랜치에도 합치고 같은 규칙을 적용시켜주시기 바랄게요~
